
"use client";

import { useState, useEffect } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { Input } from "@/components/ui/input";
import { Search, Sparkles, Filter, Globe, ArrowRight, Rocket } from "lucide-react";
import BusinessCard from "@/components/showcase/BusinessCard";
import { Button } from "@/components/ui/button";
import Link from "next/link";

interface Business {
  id: string;
  name: string;
  category: string;
  location: string;
  description: string;
  seoScore: number;
  growth: string;
  review: string;
  rating: number;
  tagline?: string;
  services?: string[];
}

const MOCK_SUCCESS_STORIES: Business[] = [
  {
    id: "m1",
    name: "Quantum Coffee Labs",
    category: "Cafe",
    location: "San Francisco, CA",
    description: "Brewing the future with precision-engineered beans and futuristic roasting techniques. We specialize in high-end caffeine experiences for the modern tech enthusiast.",
    seoScore: 94,
    growth: "140% traffic boost",
    review: "The SEO protocols implemented by LocalBoost AI put us on the map overnight. We've seen a massive surge in foot traffic.",
    rating: 5,
    tagline: "Fueling the Next Generation",
    services: ["Molecular Brewing", "Edge Roasting", "Smart Seating"]
  },
  {
    id: "m2",
    name: "Blue Door Bakery",
    category: "Food",
    location: "Austin, TX",
    description: "Artisanal breads and pastries handcrafted with local organic ingredients. A traditional approach to baking enhanced by digital marketing excellence.",
    seoScore: 88,
    growth: "2x customer reach",
    review: "A complete game changer for our small town bakery. Our digital presence finally matches the quality of our bread.",
    rating: 5,
    tagline: "Tradition Meets Tomorrow",
    services: ["Sourdough Mastery", "Vegan Pastries", "Delivery Hub"]
  },
  {
    id: "m3",
    name: "Summit Tech Repair",
    category: "Electronics",
    location: "Seattle, WA",
    description: "Expert repair services for all your high-end devices and smart home systems. Precision diagnostics and rapid turnarounds.",
    seoScore: 91,
    growth: "85% more leads",
    review: "Finally, a marketing strategy that actually works for specialized tech services. Our phone hasn't stopped ringing.",
    rating: 4,
    tagline: "Restoring Your Digital Edge",
    services: ["Circuit Diagnostics", "Logic Board Repair", "Data Recovery"]
  },
  {
    id: "m4",
    name: "Lush Garden Design",
    category: "Landscaping",
    location: "Miami, FL",
    description: "Transforming urban spaces into tropical paradises with sustainable design and smart irrigation systems.",
    seoScore: 86,
    growth: "50% more bookings",
    review: "The landing page generated by LocalBoost is simply stunning and converts like crazy. Our high-end clientele loves it.",
    rating: 5,
    tagline: "Nature, Optimized",
    services: ["Hydroponic Walls", "Xeriscaping", "Smart Irrigation"]
  },
  {
    id: "m5",
    name: "Apex Fitness Studio",
    category: "Fitness",
    location: "Chicago, IL",
    description: "High-intensity training and recovery sessions for peak human performance. Scientific coaching meets premium facilities.",
    seoScore: 92,
    growth: "3x memberships",
    review: "We dominate local search results now. The Google Maps optimization alone was worth the effort.",
    rating: 5,
    tagline: "Reach Your Peak",
    services: ["HIIT Circuits", "Cryotherapy", "Personalized Nutrition"]
  }
];

export default function BusinessesShowcase() {
  const [businesses, setBusinesses] = useState<Business[]>([]);
  const [search, setSearch] = useState("");
  const [categoryFilter, setCategoryFilter] = useState("All");

  useEffect(() => {
    const userBusinessesStr = localStorage.getItem("localboost_showcase_businesses");
    const userBusinesses = userBusinessesStr ? JSON.parse(userBusinessesStr) : [];
    setBusinesses([...userBusinesses, ...MOCK_SUCCESS_STORIES]);
  }, []);

  const filteredBusinesses = businesses.filter(b => {
    const matchesSearch = b.name.toLowerCase().includes(search.toLowerCase()) || 
                          b.category.toLowerCase().includes(search.toLowerCase());
    const matchesCategory = categoryFilter === "All" || b.category === categoryFilter;
    return matchesSearch && matchesCategory;
  });

  const categories = ["All", ...Array.from(new Set(businesses.map(b => b.category)))];

  return (
    <div className="min-h-screen pb-32">
      {/* Hero Header */}
      <section className="relative pt-32 pb-20 px-6 text-center overflow-hidden">
        <div className="absolute top-0 left-1/2 -translate-x-1/2 w-[800px] h-[300px] bg-primary/10 blur-[120px] -z-10 rounded-full" />
        
        <motion.div
          initial={{ opacity: 0, y: -20 }}
          animate={{ opacity: 1, y: 0 }}
          className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full bg-primary/10 border border-primary/20 text-primary text-xs font-bold mb-8"
        >
          <Globe className="w-4 h-4" />
          <span className="tracking-widest uppercase">Global Business Directory</span>
        </motion.div>

        <motion.h1 
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          className="text-5xl md:text-7xl font-headline font-bold mb-6 tracking-tight"
        >
          Success <span className="gradient-text">Ecosystem.</span>
        </motion.h1>
        
        <motion.p 
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.1 }}
          className="text-xl text-muted-foreground max-w-2xl mx-auto font-light leading-relaxed"
        >
          Explore the next generation of local businesses that have accelerated their growth using the LocalBoost AI engine.
        </motion.p>
      </section>

      {/* Filters & Search */}
      <section className="max-w-7xl mx-auto px-6 mb-16">
        <div className="glass-card p-6 rounded-3xl border-white/5 flex flex-col md:flex-row gap-6 items-center">
          <div className="relative flex-1 w-full">
            <Search className="absolute left-4 top-1/2 -translate-y-1/2 w-5 h-5 text-muted-foreground" />
            <Input 
              placeholder="Search by name or category..." 
              value={search}
              onChange={(e) => setSearch(e.target.value)}
              className="pl-12 h-14 bg-white/5 border-white/5 rounded-2xl focus:ring-primary"
            />
          </div>
          
          <div className="flex gap-2 overflow-x-auto pb-2 md:pb-0 scrollbar-hide w-full md:w-auto">
            {categories.map(cat => (
              <Button
                key={cat}
                variant={categoryFilter === cat ? "default" : "outline"}
                onClick={() => setCategoryFilter(cat)}
                className={`rounded-full h-12 px-6 font-bold tracking-tight transition-all ${categoryFilter === cat ? "bg-primary shadow-lg shadow-primary/20" : "border-white/10 hover:bg-white/5"}`}
              >
                {cat}
              </Button>
            ))}
          </div>
        </div>
      </section>

      {/* Grid */}
      <section className="max-w-7xl mx-auto px-6">
        {filteredBusinesses.length > 0 ? (
          <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-8">
            <AnimatePresence>
              {filteredBusinesses.map((business, idx) => (
                <motion.div
                  key={business.id}
                  layout
                  initial={{ opacity: 0, scale: 0.9 }}
                  animate={{ opacity: 1, scale: 1 }}
                  transition={{ delay: idx * 0.05 }}
                >
                  <BusinessCard business={business} />
                </motion.div>
              ))}
            </AnimatePresence>
          </div>
        ) : (
          <motion.div 
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            className="text-center py-32 space-y-6 glass-card rounded-[3rem] border-white/5"
          >
            <div className="bg-primary/10 w-20 h-20 rounded-3xl flex items-center justify-center mx-auto">
              <Sparkles className="text-primary w-10 h-10" />
            </div>
            <h2 className="text-3xl font-headline font-bold">No Businesses Found</h2>
            <p className="text-muted-foreground max-w-sm mx-auto font-light">
              We couldn't find any results for your current filter. Be the first to launch your business in this sector!
            </p>
            <Button size="lg" className="rounded-full px-10 h-14 bg-primary" asChild>
              <Link href="/dashboard">
                Launch Now <Rocket className="ml-2 w-5 h-5" />
              </Link>
            </Button>
          </motion.div>
        )}
      </section>

      {/* CTA Footer */}
      <section className="max-w-5xl mx-auto px-6 mt-32 text-center">
        <div className="glass-card p-16 rounded-[3rem] border-white/5 relative overflow-hidden group">
          <div className="absolute inset-0 bg-gradient-to-br from-primary/10 to-transparent opacity-0 group-hover:opacity-100 transition-opacity" />
          <h2 className="text-4xl font-headline font-bold mb-4">Your business could be next.</h2>
          <p className="text-muted-foreground text-lg mb-10 max-w-xl mx-auto font-light">
            Join thousands of founders who have transformed their local presence with AI-powered strategy.
          </p>
          <Button size="lg" className="rounded-full h-16 px-12 text-xl font-headline group" asChild>
            <Link href="/dashboard" className="flex items-center gap-3">
              Start Your Success Story <ArrowRight className="w-5 h-5 group-hover:translate-x-1 transition-transform" />
            </Link>
          </Button>
        </div>
      </section>
    </div>
  );
}
